### ISSUE TITLE
Research: Tiny House [on Wheels] in Portugal 🏠 🔍 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phase-three#120]
We recently concluded that shipping container homes 
(difficult/expensive to move if the council/neighbors complain) 
are a no-go for temporary accommodation on rural land in PT. 
Basically if the structure cannot be _easily_ moved it is considered permanent for licensing/legal reasons.
See: https://github.com/dwyl/phase-three/issues/114#issuecomment-1227069738

A Tiny House on Wheels is very clearly a non-permanent structure and therefore not considered permanent.
But there will still be rules that need to be followed.

We found the following recently published/updated [06 July 2022] on a prominent property website:
https://www.imovirtual.com/en/noticias/lifestyle/tiny-house-portugal-legislacao-como-comprar
<img width="983" alt="image" src="https://user-images.githubusercontent.com/194400/188397728-20939cdb-4643-4b3e-bcd4-ca3691495057.png">

<img width="798" alt="image" src="https://user-images.githubusercontent.com/194400/188646948-595487b0-2228-49fa-b82c-10ecdb56bf9b.png">

PDF snapshot: [Tiny-House-em-Portugal_Legislacao-e-como-comprar_Imovirtual.pdf](https://github.com/dwyl/phase-three/files/9487847/Tiny-House-em-Portugal_Legislacao-e-como-comprar_Imovirtual.pdf)

## Precedent 

Consider the following AirBnB Listing in the Óbidos, Leiria District: https://www.airbnb.com/rooms/39025493

<img width="976" alt="image" src="https://user-images.githubusercontent.com/194400/188645839-def37e48-879f-4d4d-9095-18cb8d669182.png">

<img width="679" alt="image" src="https://user-images.githubusercontent.com/194400/188647384-d65cc148-2fd9-4222-bdc9-a568f1876a33.png">

It's **`€47/night`** but offers no facilities / features / activities beyond the tiny house.
i.e. no pool or other water access. **Óbidos** is **`3km`** away and the beach is **`10km`**. 

## Portuguese Tiny House Builders

There are a few companies making tiny houses on wheels in PT:

https://tinyhousesfactory.pt/tiny-houses/modern/
<img width="912" alt="image" src="https://user-images.githubusercontent.com/194400/188584906-0b90680f-5be7-4fc1-84c7-e8742458cd49.png">

Based just outside Porto: https://swtbuilding.pt/produtos/tiny-house/
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/194400/188584953-81d7bbd5-8b96-412f-8b89-a6ac9b109e8c.png">

http://www.tinyhouseportugal.com/prices.html
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/194400/188634834-ebd8fa8d-a9b3-46ec-8bc4-bfb6c05119e1.png">

We should research if there are more and find out:
a) where they are based
b) what their availability for a visit/consultation is
c) lead times for building a Tiny Home

# Todo 

+ [ ] Call the 3 Tiny House builders listed above and find out more;
  + [ ] You want to buy a "retired person" friendly Tiny House for your parents to stay in on rustic land
  > Tell them your budget is flexible but you would prefer to know from them how much they would expect to charge in 2022.
+ [ ] Research other Tiny House Builders in PT [Google Skills]
(please leave comments below with screenshots, website and details of where they are based)
  + [ ] Ideally look for reviews from people who have purchased from the suppliers 🤞 but if not, screenshots! 📷 
+ [ ] Call **`Cinfães`** Council (Câmara Municipal): https://cm-cinfaes.pt/contactos
  + [ ] Ask them if there is any precendent for people putting Tiny Houses on Wheels on Land in their area.
  + [ ] Find out who is responsible for planning in the Câmara and if we can get a meeting with them. (either face-to-face or Virtual)

@Stephanymtr would you mind picking this up today? 🙏

**Comment by Stephanymtr** [comment]
About my call to the following companies:
- https://tinyhousesfactory.pt/
They are closed at the moment - on holiday. They asked to return the call on September 16th. 
- https://swtbuilding.pt/produtos/tiny-house/
I spoke with their secretary on the phone, and she explained only the professionals (architect/engineer) could give an estimate. It's not done over the phone as there are lot of information they need to collect first e.g, size, materials , finishes, requirements etc. The best way to understand how much a tiny home will cost is to schedule a meeting in person at their office. Their office is at  Rua Poeta Dário Bastos n.º 68/100 - Baguim do Monte / call or email to schedule a visit geral@swt.pt 
-http://www.tinyhouseportugal.com/prices.html
They said the same as above: schedule a visit to speak with them about all the medidas e materiais that you will want to use, so that they can give you a more precise estimate. He also said that the prices online on their website are NOT correct. Prices of materials change every month - It's about 25% more than what is showing on there. They have to collected all the size, materials , finishes, requirements etc. information and then look up what the price of the materials will cost to put a orcamento together.

**Comment by nelsonic** [comment]
Ok. the SWT we could visit on Friday on the way to/from visiting the land (CC: @iteles) https://github.com/dwyl/phase-three/issues/116#issuecomment-1238902138

**Comment by nelsonic** [comment]
https://www.airbnb.com/rooms/4462366 **`€65/night`**:
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/194400/188883815-2b2ff9fc-039c-4da6-ac47-f0754b9d73f6.png">

Looks great from the outside:
<img width="756" alt="image" src="https://user-images.githubusercontent.com/194400/188884727-8d0b38bd-eca6-4d7f-b454-14db654e841d.png">

Fixtures/fittings are a bit "rustic":
<img width="324" alt="image" src="https://user-images.githubusercontent.com/194400/188884229-6b9f7752-cc74-41ae-b974-078b837bc8a4.png">

![image](https://user-images.githubusercontent.com/194400/188884551-59cf52c6-b13d-48f0-a0e2-acb8444b6dc9.png)
<img width="756" alt="image" src="https://user-images.githubusercontent.com/194400/188884633-181d8572-1668-440e-bd3b-062fbf963491.png">

**Comment by iteles** [comment]
@nelsonic SWT is 51 mins away from the land in #116, which is then another 50 mins from home in Braga.
We're going to struggle to do it all in one day depending how long you want to stay at the land.

<img width="887" alt="image" src="https://user-images.githubusercontent.com/4185328/188915777-16f175d8-17c1-4de9-bc81-1ea601c83826.png">

**Comment by nelsonic** [comment]
@iteles given that you have request to change the property viewing time and we have both S & Gui on Friday, can we just take the day to get as much work done as possible? 💭

**Comment by iteles** [comment]
I will call SWT in the morning and see if we can book a meeting.

**Comment by nelsonic** [comment]
Yeah, s'plain to them that we will be buying at _least_ one Tiny Home and want to collab on building **10 homes** for an eco tiny house village and see if they have time to meet. 😜

**Comment by nelsonic** [comment]
Not related to meeting with **`SWT`** but my research into Tiny Homes has lead me to consider agricultural trailers as a means of getting considerably more house for the same trailer money, see: #123 💭

**Comment by Stephanymtr** [comment]
https://youtu.be/Bx4nwu8ahiI

**Comment by nelsonic** [comment]
@Stephanymtr great episode, thanks for sharing. [ updated with a screenshot ] 🎉 
We subbed to "Our Rich Journey" a while back ... These guys are awesome! 😍 

CC: @LuchoTurtle "F.I.R.E" 🔥

**Comment by Stephanymtr** [comment]
yes, I thought that was bit high too. I know they have hired 3rd party company to do the cleaning of their current Airbnb. I also highly doubt they will be the ones managing this property, so they will need a team to take care of their guests 24/7. It's a small house, and they are building right next to the big airbnb mansion they acquired recently, so maybe the cleaning team will spend another hour cleaning and those kind of costs won't be as high ?!

This is the location: Ortigosa, Leiria, Portugal
<img width="462" alt="Screenshot 2022-09-08 at 12 02 07" src="https://user-images.githubusercontent.com/91985721/189106196-88c3aee5-ca34-4e84-b2d0-0152eb7b1b98.png">

<img width="1181" alt="Screenshot 2022-09-08 at 12 00 52" src="https://user-images.githubusercontent.com/91985721/189105974-8b214429-4381-4599-9496-8472ae954fbc.png">
Price of stay for 6 days

https://www.airbnb.com/rooms/50524896?source_impression_id=p3_1662634771_i9iWVu%2FwinMdaKro

**Comment by Stephanymtr** [comment]
CASAGAEA https://casagaea.eu/en/
Factory and Showroom -Rua Fonte dos Anjos, 6 4700-565 Mire de Tibães ,Braga - Portugal
910428481 
<img width="1369" alt="Screenshot 2022-09-08 at 12 09 14" src="https://user-images.githubusercontent.com/91985721/189108292-fa35a7e5-cd8b-476a-99f3-25272443069d.png">
i
<img width="1175" alt="Screenshot 2022-09-08 at 12 12 57" src="https://user-images.githubusercontent.com/91985721/189108297-f161c146-1dc0-4583-84ee-43b3e964caf5.png">
 Super close! I tried contacting them just now, but I wasn't able to reach anyone. I also wasn't able to find reviews, but they are very present online on their social media accounts.

**Comment by Stephanymtr** [comment]
While looking for Tiny House Builders, I bumped into this website https://www.nature.house/tiny-house-portugal
<img width="1295" alt="Screenshot 2022-09-08 at 13 32 54" src="https://user-images.githubusercontent.com/91985721/189122703-5725b56b-73d6-4df9-a233-9a2ddda63f99.png">

**Comment by Stephanymtr** [comment]
Box Code
Tel: +351 916 181 342
Email: [hello@boxcode.pt](mailto:hello@boxcode.pt)
Email: boxcodept@gmail.com (Paulo Oliveira's personal email - person who I talked to on the phone, SUPER chatty, we said the company is growing; he has clients from all over the world; he is starting a 2nd building location up north in Braga ; He designs tiny homes specifically for Airbnb hosts as well... He said tiny houses are around 40-60k, but it depends on a lot of the materials the clients prefers. I said we'd email him if/when we are ready to schedule a call - since they are all the day in: 

Rua Lucinda do Carmo N 20
Almada, 2855-699 Portugal
https://www.boxcode.pt/

<img width="993" alt="Screenshot 2022-09-08 at 13 37 00" src="https://user-images.githubusercontent.com/91985721/189123462-a7ffc5ff-ddef-4d94-bddf-57e1748bd08d.png">

**Comment by Stephanymtr** [comment]
Finally, numbers! They provide an estimate which is pretty cool.
https://tinyhouse-world.com/tiny-house-kaufen/
I called them, but no one picked up. I was able to find out where they are located. Based on the phone number, they seem to be a Germany company. They do design and build tiny homes in many countries including Portugal. 
+49 157 85077832

<img width="764" alt="Screenshot 2022-09-08 at 14 07 12" src="https://user-images.githubusercontent.com/91985721/189129782-dc226496-9c1c-45c7-9852-55fefd069838.png">
<img width="758" alt="Screenshot 2022-09-08 at 14 07 25" src="https://user-images.githubusercontent.com/91985721/189129784-92395cb7-ffba-49b4-a203-4e858c2e807a.png">

https://tinyhouse-world.com/our-tiny-houses/standard-tiny-house/

<img width="863" alt="Screenshot 2022-09-08 at 14 15 25" src="https://user-images.githubusercontent.com/91985721/189131513-3959a2c1-9206-4b16-9077-ee3b698a67af.png">

**Comment by Stephanymtr** [comment]
Madeiguincho
https://www.madeiguincho.pt/ 
[(351) 917 161 865](tel:+351917161865)
[info@madeiguincho.pt](mailto:info@madeiguincho.pt)
Rua do Casal Queimado, Nº12
2750-492  Cascais - Portugal
<img width="1356" alt="Screenshot 2022-09-08 at 14 21 24" src="https://user-images.githubusercontent.com/91985721/189133304-ae717988-a2fe-4b30-8daf-7596485ea562.png">
<img width="432" alt="Screenshot 2022-09-08 at 14 20 57" src="https://user-images.githubusercontent.com/91985721/189133298-f765bb24-9529-4142-b485-b11c2fd0f0f3.png">

Loads of positive reviews on Google
<img width="717" alt="Screenshot 2022-09-08 at 14 24 33" src="https://user-images.githubusercontent.com/91985721/189134028-9e7e1bd4-167c-477f-8bb0-d8adf74e7121.png">

**Comment by nelsonic** [comment]
Madeiraguincho https://www.madeiguincho.pt/tree-houses is base very close to Inês' brother's house. 
They have some great tiny/tree houses in their gallery. 
I'd love to visit them next time we are down south. 💭

**Comment by Stephanymtr** [comment]
@nelsonic I contacted Cinfães Council, and I spoke to Conceição, a telefonista da Câmara. She was unable to give me any information regarding precedents for people putting Tiny Houses on Wheels on Land in their area. However, she did say we could speak with the Câmara's architect or engineer regarding this subject. _They are both on vacation_ and will not be back until September 19th ⏳ The best way to contact them and schedule a meeting is via email:

Eng.ª Cidália Mendes | [cidalia.mendes@cm-cinfaes.pt](mailto:cidalia.mendes@cm-cinfaes.pt)
3.ª e 6.ª
14:00 - 16:00 | Por agendamento
Arq.º André Melo | [andre.melo@cm-cinfaes.pt](mailto:andre.melo@cm-cinfaes.pt)
4.ª e 6.ª
9:30 - 13:00 | Por agendamento

Obs: Conceição suggested emailing Andre, the architect. I'm not sure why - maybe he is nicer 😆. I looked up the engineer email information as well in case you want to contact both.

**Comment by nelsonic** [comment]
Yesterday we visited **`SWT`** https://github.com/dwyl/tiny-house/issues/20 
It was an insightful and we had a good factory tour:

<img width="676" alt="image" src="https://user-images.githubusercontent.com/194400/189477119-46fadc6e-1a16-42e3-aeb4-297443940541.png">

But ultimately, they are building Steel Frame pre-fabricated houses 
that are _small_ by the definition of a traditional house,
but they aren't "_tiny_".

So far, of all the _existing_ Tiny House (on wheels) builders in PT, 
**MiniCasas** appears to be the best (closest to what we need); 
**`GOTO`** dedicated issue:  https://github.com/dwyl/tiny-house/issues/19
