### ISSUE TITLE
Research: Cheap Caravan for Temporary Living

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phase-three#128]
Please note: we are **_definitely_ not** considering _living_ in a Caravan long-term. ⛺ 
However if we buy _any_ land that doesn't have _existing_ living quarters e.g: #116 
we will need _something_ either for _ourselves_ to stay in _short-term_. 
***or*** for an on-site construction worker to live in, again, _short-term_. 

# Todo

Please: search OLX, [Stand Virtual](https://www.standvirtual.com/) and any other websites where these sorts of things are sold
and share links to the listings you find that are relevant to us. 

+ [ ] ***Research*** available reasonably priced [Budget: **`€10k`**] caravans that we can use short-term.
  > **Note**:  We don't want (have _time_ for) a "fixer-upper" caravan; it _must_ be immediately liveable with minimal cleaning.
  > Once we no longer need the caravan it will be re-sold at a small loss e.g: **`€7k`** 

+ [ ] **Sleeps 4** people. 4️⃣ 
  > **Note**: if you find smaller caravans that sleep **2 people** but still have OK facilities [see below] (toilet, shower & kitchenette), 
please share as these will interest us for workpeople/workawayers #119 
Smaller caravans should be correspondingly cheaper e.g. **`€6k`**.

+ [ ] Desireable facilities: 
  + [ ] Toilet 🚽 
  + [ ] Shower 🛒 
  + [ ] Kitchenette (most likely propane/butane based ...) 🍴 
  + [ ] Solar Panel + batteries ☀️ 
  + [ ] Road-worthy (for re-saleability ...)

Example of the _kind_ of thing we are looking for: 
https://www.olx.pt/d/anuncio/caravana-sterling-europa-de-luxo-em-boa-condicao-IDHjK7J.html#ae20fee65b
<img width="1353" alt="image" src="https://user-images.githubusercontent.com/194400/191419412-0fbb45bf-8b54-423d-a4d2-e1b7a359ce58.png">

<img width="774" alt="image" src="https://user-images.githubusercontent.com/194400/191419536-7861abb6-d037-43e5-8d81-b30dd98b3086.png">

<img width="808" alt="image" src="https://user-images.githubusercontent.com/194400/191419596-7629a9e4-c80f-44c5-a2b9-3a122afef481.png">

**Comment by nelsonic** [comment]
FYI: apparently renting a caravan on AirBnB is a thing in PT: https://www.airbnb.co.uk/rooms/32442749

<img width="1039" alt="image" src="https://user-images.githubusercontent.com/194400/191459566-7244e2c3-1729-4ff1-879a-7130081a62bc.png">

**`€16/night`** for 2 people is a bargain. 

But the caravan is _ooooollllddd_ ... 

![image](https://user-images.githubusercontent.com/194400/191458251-13bea00f-efd2-40e0-9a95-193d5b51c515.png)

The caravan doesn't have any W/C or shower, these are located in an out-house:
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/194400/191458614-72ba64f8-1f99-4e47-a52a-3b16b87fc066.png">

<img width="776" alt="image" src="https://user-images.githubusercontent.com/194400/191458703-906b2fd5-be76-4ab8-9053-38d0fc7c4957.png">

They are very much playing up the nature angle: 
<img width="773" alt="image" src="https://user-images.githubusercontent.com/194400/191458796-719dcb9c-a584-4ab6-97d7-8409160b6ab8.png">

The AirBnB Listing location is "São João das Lampas, Lisboa, Portugal"

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/194400/191458065-ac19cf8f-13c1-4682-8249-9dffba6d3ef5.png">

As you can tell from the map it's quite far from Lisbon ... 

All this to say: a Caravan could be a totally viable AirBnB option on the land in the short to medium term. 
Reviews are good: 
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/194400/191459263-5b2306d0-efd0-4cc1-9fb3-628fc55339b7.png">

We could probably get **`€20/night`**.  Not going to make bank with this kind of cash but it could _gradually_ pay for the caravan.  The _interesting_ version of this would be getting _foreign_ families to spend a week at a time with airport transfer.
We could get **`€180/week`** and do **12 weeks** a year it's **`€2,160/year`**.
At _those_ sort of numbers it would pay for itself pretty quickly. 
But we are not, I _repeat_ ***NOT*** building a "caravan park" under any circumstances!!
This would be a short-term stop gap for _us_ to stay in on weekends while the "main" house is being built. 

Please share your research on potential caravans we can buy. 🙏

**Comment by nelsonic** [comment]
https://www.olx.pt/d/anuncio/caravana-inglesa-quarto-wc-separados-IDHlgBc.html
![image](https://user-images.githubusercontent.com/194400/192220178-2bc899f3-9d70-43d7-9538-22c1b48f3000.png)

![image](https://user-images.githubusercontent.com/194400/192222211-fbac47ff-aa55-419d-a829-a471ab13698f.png)

Google translate: 

![image](https://user-images.githubusercontent.com/194400/192223004-3f29e48d-5ad9-47ff-a5ac-5bee29b92a86.png)

Interior:

![image](https://user-images.githubusercontent.com/194400/192220247-34a59795-d486-4969-8dc1-aa09dc41c69b.png)
![image](https://user-images.githubusercontent.com/194400/192220279-17e20f00-3c25-4df4-8ba8-bc4ffc811f0e.png)

Looks like it's in very good condition.

**Comment by nelsonic** [comment]
@iteles looking at the prices of the TinyHousePortugal you shared on https://github.com/dwyl/tiny-house/issues/21#issuecomment-2625274866  **31500€ + IVA trailer** 💰 
I feel like a _used_ (but still great condition) caravan is a _much_ better option in the short-term.  💭


https://www.olx.pt/d/anuncio/caravana-inglesa-ranger-IDIH3pC.html
<img width="1341" alt="Image" src="https://github.com/user-attachments/assets/6e681612-0921-4a1e-be08-f4086297a651" />

![Image](https://github.com/user-attachments/assets/232939b2-a521-4483-9867-b4f0a274547b)

![Image](https://github.com/user-attachments/assets/d4db7c1f-b012-4c4c-8db8-db11c70e45dc)

![Image](https://github.com/user-attachments/assets/d271ed2a-47f7-4e54-894b-018f0ce8c459)

![Image](https://github.com/user-attachments/assets/df534a2c-73c0-47a8-95ff-dee83d57a2fb)

![Image](https://github.com/user-attachments/assets/3d6e9550-9b62-4ed9-b504-f8a0ab5b6b65)

![Image](https://github.com/user-attachments/assets/27eba350-1ff5-4d58-aaf0-cacd6b73a7eb)

This seller appears to have a few of them that they have imported from the UK: 
https://www.olx.pt/ads/user/l9aiD/?query=caravana

<img width="1340" alt="Image" src="https://github.com/user-attachments/assets/55db2b24-6c22-4834-9324-a8be026275e0" />

The `SONATA` looks even better maintained: 
https://www.olx.pt/d/anuncio/caravana-inglesa-sonata-IDIIpwi.html

<img width="1318" alt="Image" src="https://github.com/user-attachments/assets/ec67163b-8d51-4960-9909-4018786647c6" />




They have made an effort with their website: https://dfccars.pt

https://dfccars.pt/contactos#location

<img width="1363" alt="Image" src="https://github.com/user-attachments/assets/3454e0df-e63b-4fa6-8773-33fd8edc60f5" />


`T2h` drive from @home https://maps.app.goo.gl/psJYc9k45RGXEwTd6
<img width="1226" alt="Image" src="https://github.com/user-attachments/assets/44e46e93-3444-4757-87f7-c8bb33dd7a3b" />

We could go down to `Coimbra` to `Portugal dos Pequenos` https://www.fbb.pt/pp/
and or Lousã: https://www.booking.com/hotel/pt/octant-lousa.en-gb.html

We could visit your Mum's Cuz at Aldeias do Xisto for a night or two:
https://www.tripadvisor.pt/Attraction_Review-g1769086-d10472744-Reviews-Aldeias_do_Xisto-Lousa_Coimbra_District_Central_Portugal.html
<img width="1284" alt="Image" src="https://github.com/user-attachments/assets/bf8f6029-45b8-41b0-9fae-b28315172b18" />

@iteles thoughts?

**Comment by carolrmc** [comment]
There are some very good vans reasonably priced. 
It's a great choice for a tiny house substitute, especially if you put a veranda extension.

**Comment by iteles** [comment]
Wasn't really in a frame of mind to be looking at this stuff at the end of Jan when we lost childcare and I was unwell, but will need to revive this soon.
