### ISSUE TITLE
Cultivating Industrial Hemp for Fibres/Hempcrete | Cultivo de Cânhamo 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phase-three#131]
Hemp fibre is widely used in industry and agriculture.
It's been grown for rope, fabric and construction purposes for millennia. 
Growing it in PT has been legal - but regulated - since 2004:

https://www.dgav.pt/plantas/conteudo/autorizacoes-de-cultivo/cultivo-de-canhamo/
![image](https://user-images.githubusercontent.com/194400/192833689-6f158918-c6a6-4be1-8eb8-d88debd29929.png)

https://www.zoomalia.pt/animais/substrato-natural-de-canhamo-para-coelhos-e-animais-roedores-100-natural-30l-150l-et-200l-quality-clean-p-50372.html
![image](https://user-images.githubusercontent.com/194400/192834207-aa83ba2d-a735-49d3-a8b1-71215eebc982.png)

> Please note: https://en.wikipedia.org/wiki/Hemp is in the same _family as https://en.wikipedia.org/wiki/Cannabis but is ***NOT*** the kind that has THC.

# Todo

+ [ ] Investigate if we can grow it.
+ [ ] Write-up the process for getting a license to see if it's worth our while to grow it ourselves or to just pay someone else for the hemp fibres. 
+ [ ] is there an _annual_ (or other frequency) inspection and fees to pay for the license? 
  + [ ] will this cost out-weigh the benefits at our relatively small scale?
