### ISSUE TITLE
Bamboo 🌱 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phase-three#133]
Feels like a glaring omission that **`babmoo`** is not mentioned _anywhere_ in this repo ... [phase-three/issues?q=bamboo](https://github.com/dwyl/phase-three/issues?q=is%3Aissue+is%3Aopen+bamboo) 🔍 🤷‍♂️ 
![image](https://user-images.githubusercontent.com/194400/194051222-a1b645f1-2c2c-4a7c-9b0c-99ac26cc74db.png)

Let's _fix_ that!!

# What?

Bamboos are a diverse group of [evergreen](https://en.wikipedia.org/wiki/Evergreen) [perennial](https://en.wikipedia.org/wiki/Perennial_plant) flowering plants making up the [subfamily](https://en.wikipedia.org/wiki/Subfamily_(biology)) Bambusoideae of the grass family [Poaceae](https://en.wikipedia.org/wiki/Poaceae). [Giant bamboos](https://en.wikipedia.org/wiki/Giant_bamboo) are the largest members of the grass family. The origin of the word "bamboo" is uncertain, but it probably comes from the [Dutch](https://en.wikipedia.org/wiki/Dutch_language) or [Portuguese](https://en.wikipedia.org/wiki/Portuguese_language) language, which originally borrowed it from [Malay](https://en.wikipedia.org/wiki/Malay_language) or [Kannada](https://en.wikipedia.org/wiki/Kannada_language). [wikipedia.org/wiki/Bamboo](https://en.wikipedia.org/wiki/Bamboo)

## Nitrogen Fixing Air-freshening Carbon Sink

**`Babmoo`** is an _excellent_ photosynthesizer, converting CO<sub>2</sub> into Oxygen
and is a net carbon sink over its' growing cycle/lifetime. see: [nature.com/articles/nindia.2021.46](https://www.nature.com/articles/nindia.2021.46)

## _Many_ Uses

There are _many_ practical uses for **`babmoo`**, here are our **Top 5**:

1. Evergreen privacy living barrier / fence / hedge
2. Canes for supporting growing trees
3. Building material e.g. for decking, pergolas, tree houses, scaffolding, etc.
4. Food: edible shoots
5. Paper, Fabric and other derived products!

## Won't it spread and _take over_?

There is a misconception that **`babmoo`** "takes over" any area if given the chance.
Yes, it grows _fast_ and spreads if there is space, fertile soil and abundant water.
But it will take years if not _decades_ to "take over" and create a **`babmoo`** ***forest***. 

With _planning_, segmentation and root-blocking we can _easily_ confine the **`babmoo`** to a well-defined area. 
And since we intend to harvest several canes each year to use around the land.

# How?

How to Grow, Maintain and Control Bamboo | Our Japanese Garden Escape: https://youtu.be/v9LwbriCRgE
[![image](https://user-images.githubusercontent.com/194400/194051510-8413ee36-3dee-4011-a1ea-90b757c4d516.png)](https://youtu.be/v9LwbriCRgE)

# Todo

+ [ ] ***Research*** which species are _allowed_ and _available_ in PT
+ [ ] ***Source*** at least **10 varieties** including **small**, **medium** and ***giant*** (if we can grow more varieties especially edibles, we should totally add more!)
+ [ ] ***Plan*** the areas where we want to grow the different varieties
+ [ ] **Prepare** the area with barriers to prevent over-spreading
+ [ ] **Plant!**

**Comment by nelsonic** [comment]
For a great overview of how Bamboo is _already_ used in eastern architecture and how innovative European architects are using it in future buildings, watch: 

Bamboo--the Tradition of the Future: https://youtu.be/tKcyrlysQwA
[![image](https://user-images.githubusercontent.com/194400/194160464-fcb38797-517f-4ca6-a950-5297582850cb.png)](https://youtu.be/tKcyrlysQwA)

**Comment by nelsonic** [comment]
BAMBOO GALORE!! FULL TOUR of over 30 Varieties @ Sandhill Farm: https://youtu.be/1SKCrG-3kEc
[![image](https://user-images.githubusercontent.com/194400/194220935-87794cc4-fbbc-4494-a637-6288ef867115.png)](https://youtu.be/1SKCrG-3kEc)

**Comment by nelsonic** [comment]
Magical houses, made of bamboo | Elora Hardy: https://youtu.be/kK_UjBmHqQw [TED Talk]

**Comment by nelsonic** [comment]
TP made from Bamboo:
The Good Roll: wiping out non sustainable practices in toilet paper production: https://youtu.be/fxveBumsRmo
<img width="932" alt="image" src="https://user-images.githubusercontent.com/194400/197037595-47632eb6-7d10-4f21-9f30-d37ddd10f0d5.png">

**Comment by nelsonic** [comment]
Preserving Bamboo so it lasts _much_ longer: 

https://www.youtube.com/watch?v=Zc7G5eN4N3g&t=175s
<img width="1272" alt="image" src="https://github.com/dwyl/phase-three/assets/194400/4d790fed-9401-44e6-89a8-aaa3f08805c5">

6% borax
4% boric acid
90% water

Make Bamboo last for _decades_: https://youtu.be/Aghf4j9ly8A

**Comment by nelsonic** [comment]
Boric Acid ("Ácido Borico") can be purchased in a bulk sack for **`€79`** (+€3,89 shipping) = `€83` for **`25kg`** = €3.32/kg

<img width="1197" alt="image" src="https://github.com/dwyl/phase-three/assets/194400/62e80b42-d1da-4a7c-8d7c-9b0c5947247b">

This is a totally reasonable price considering that it can make _hundreds_ of bamboo canes we can use for _many_ purposes. 💭

**Comment by iteles** [comment]
The only thing that isn't mentioned so far in this issue is researching how we can keep the bamboo _non-dense_ ('thin' didn't feel like the right word) to avoid them becoming a home for rodents and other pests 👌🏻

**Comment by nelsonic** [comment]
@iteles I’m not even slightly concerned about rodents/“pests”. When we have Bamboo we will 100% have a cat. 🐈 
But perhaps the best person to axsk is Ricardo (Landim caretaker) if there are rats in the bamboo near the water tank. I certainly haven’t seen any signs of them. 💭

**Comment by iteles** [comment]
There are plenty of mice in Landim and a few rats too, hard to pinpoint where from - but they have dogs that catch them on the regular.

**Comment by nelsonic** [comment]
“Plenty of mice” 🐁…
In the bamboo? 🤷‍♂️
Or just because it’s a wedding venue and people drop food which doesn’t get fully cleaned up … 💭
Mice are an _essential_ element in a forest/farm ecosystem and they ensure you will have Owls! 🦉 
The question is: does the Bamboo create a “infestation” problem because no predators (the dogs) can reach the rodents…? 🤔
I’d still have a Cat (or two!) if I were Landim. 🐈‍⬛ 
They are _muuuch_ better at hunting/catching/killing mice/rats than dogs! 🐕

**Comment by nelsonic** [comment]
How Bamboo Can Invade Your House: https://www.core77.com/posts/133313/How-Bamboo-Can-Invade-Your-House
Incredible photos! Especially of the shoots pushing through asphalt! 
Via: https://news.ycombinator.com/item?id=41254622 (no insightful comments tho…)

**Comment by carolrmc** [comment]
Scary, almost sinister!
