### ISSUE TITLE
Research: Motorhome (Autocaravana)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phase-three#147]
As noted in #128 a caravan is still a _solid_ `<option>` for temporary/weekend living on land if we are able to buy some ... #116 💭 
But as progress has been _sloooow_ with purchasing the land and @carolrmc's retirement approaches _rapidly_, 🎉 
it's time to consider a "Tiny Home on Wheels" that they can take on a Road Trip across Europe to visit Family & Friends! 🚌 

# Todo ✅ 

+ [ ] Research Motorhomes in `PT` (already legalised), `UK` (cheaper / better value), `NL` (_much_ cheaper).
Must have:
  + [ ] Full Toilet
  + [ ] `Deisel`  engine (for easy of refuelling across Europe) ⛽
    > this could be converted to Electric ⚡ 🔋  at a later date or simply parked on land.
  + [ ] Space for Cat 🐈‍⬛ to join on the road trip! 
+ [ ] Budget **`€25k`** (more if it's a _great_ deal that will retain value, i.e. won't depreciate fast ...)

I've been searching on https://www.autotrader.co.uk https://camper.nl and https://www.olx.pt ...
There are _many_ options but we'd either need to spend like `€80-120k` on something _amazing_ (which blows our budget absurdly...) ***or*** we buy something _reasonably_ priced with a good chasis/mechanics that we can enhance!

# Enhancements ✨ 

In _descending_ order of cost: ⬇️ 

+ [ ] **Solar panels**! I would _max_ out the number of panels on the roof and have enough batteries to be able to run an `electric` water heater for showers and washing up. ☀️ 🔋 🫖 
+ [ ] Windscreen protection film; usually around `€300` but _totally_ worth it to reduce chips/cracks! 
  > see: https://youtu.be/8rg5bTZxWu8 good for a long road trip where replacing the windscreen would be _painful_.
+ [ ] Mains power hookup if not already available - most campsites will have optional power. 🔌 
+ [ ] **_Electric_** (`12v`) Water heater - which will work off the batteries/solar power 💧 
+ [ ] **_Electric_ Induction Hob** - also off batteries/mains power
+ [ ] Security system - if not already present
+ [ ] Rear Camera for reversing/parking - thankfully these are dirt cheap these days! 🎥 
  https://www.aliexpress.com/w/wholesale-reversing-camera.html
+ [ ] Radar parking sensors - thse can be mounted on rear _and_ front to reduce bumps. 🔘 
Also dirt cheap from `CN`: https://www.aliexpress.com/w/wholesale-parking-sensors.html
+ [ ] Electrical sockets for charging devices (if not already present). 📱 💻 etc.

@carolrmc I probably haven't captured all your requirements ...
Please free to leave a comment with more detail if/when you have time. 

There are _many_ good lists online for accessories for Motorhomes, e.g:
+ 50 Essential Accessories, Gadgets and Equipment for Your Motorhome: 
  https://omcmotorhomes.co.uk/motorhome-accessories-and-equipment/
+ Must-have Items For Making Your Motorhome Feel Like Home:
https://www.rvsupercentre.co.nz/blog/our-blog/buyer-guides/must-have-items-for-your-motorhome/

**Comment by nelsonic** [comment]
Example I thought was good: 

https://www.olx.pt/d/anuncio/autocaravana-mercedes-integral-IDIkrB2.html?
<img width="1327" alt="image" src="https://github.com/dwyl/phase-three/assets/194400/887ceb05-de6e-4d65-960e-5d6095bfc03e">

# Descrição
```
Autocaravana Mercedes Integral.
Em bom estado Geral.
6 lugares de livrete.
6 dormidas.

Cozinha completa ,com lava louça, frigorífico e fogão.
Tem casa de banho completa.
Tem aquecimento central truma.
Depósito de águas limpas e de águas sujas.

Autocaravana com energia autônoma.
Painel solar de 80w e bateria.

Revisões em dia, incluindo 4 pneus novos.
Inspeção e iuc até 03/2025.
Mecanica em excelente estado.

Conduzida com carta B, ligeiros.
Todos os documentos em dia.
```

# Photos

Right side:
![image](https://github.com/dwyl/phase-three/assets/194400/13f2f83f-5b7c-4bf8-9f62-81ea6bed622e)

Left has main door: 
![image](https://github.com/dwyl/phase-three/assets/194400/a9e404af-1a1e-4120-b033-9581bdff68ce)

Rear end:  shows water and fuel access points
![image](https://github.com/dwyl/phase-three/assets/194400/369ab32c-4c7e-4569-97d6-5b98aa6b0b61)

Right rear:
![image](https://github.com/dwyl/phase-three/assets/194400/31e8b509-ac42-4758-9d8e-b26833bc3812)

Cabin interior: sturdy leather seats and good visibility:
![image](https://github.com/dwyl/phase-three/assets/194400/8ca0d95d-180c-4c24-90ab-77f61c367fe7)

Galley and dining area in good (wood) materials and leather; durable and easy to wipe clean:
![image](https://github.com/dwyl/phase-three/assets/194400/debe0e0e-0b34-4a7d-84b0-6a8c82787506)

Gas cooker and LED lighting:
![image](https://github.com/dwyl/phase-three/assets/194400/0c851198-b86f-4ab4-91bb-1af0128241fc)

Full bathroom with "cassette" toilet, full size sink, shower and ventilation:
![image](https://github.com/dwyl/phase-three/assets/194400/1acb661a-7292-479b-9d51-8565b6819368)

Two bunk beds: 
![image](https://github.com/dwyl/phase-three/assets/194400/bb34cced-903e-47c0-9a2a-988250b879ba)

Dining area frontal view: 
![image](https://github.com/dwyl/phase-three/assets/194400/5f117cd7-e4a9-4ab7-83b1-16ade0fda01b)

Front fold-down bed:
![image](https://github.com/dwyl/phase-three/assets/194400/d8e7f110-c321-4bad-92e7-81932adb85a0)



I sent the seller a message on OLX asking about the motor/mechanicals of it and he replied: 
![image](https://github.com/dwyl/phase-three/assets/194400/252afe59-0cd3-4d10-847c-c8552303aa39)

```md
it has 2.4 D engine.
With three hundred thousand km.
In good mechanical condition.
```

# Pros

1. Affordable entry price of `€12,650` (negotiable) 
2. Factory-built to be a motorhome, not a retrofit/conversion - so no issues with legalising it.
3. Full shower & bathroom - we've learned this is _not_ optional from our "VanLife" research
4. Already has a solar panel and battery. 
But the flat roof means we could add a few more to run more appliances 
e.g: kettle, coffee machine and induction cooker to avoid having to use (non-renewable) `Gas`. 

> Design: I quite like this "retro" (boxy) look with the two tone paint job and flat surfaces. 

# Cons

1. Leather seats might not be everyone's taste. 
May require some heavy-duty fabric covers with elastics to protect from cat claws. 
2. Dated decor especially the bathroom sink. (but the rest looks like well-maintained _real_ wood!)
3. Might not be very fuel-efficient with the "boxy" design
4. No rear window for visibility. Mitigated by having a reversing camera. 
5. Limited storage. Overcome by travelling minimalist ...

**Comment by nelsonic** [comment]
Clarice shared this one: https://www.autotrader.co.uk/motorhome-details/202405199875184
<img width="1310" alt="image" src="https://github.com/dwyl/phase-three/assets/194400/4e8d854b-b1b6-43bb-b70b-5dc4bdb75d3e">

# Description

```
Good specification 4-Berth m Motorhome including seating area for 4 persons plus three rear seatbelts. Fixed double bed plus dinette bed 2 plus 2, Separate bathroom with shower, sink and WC. Kitchen has a built in hob, fridge/ freezer, sink and good worktop area. Heating and hot water system, TV aerial and TV wall bracket. Fitted retractable awning on offside of vehicle, electric hook-up. Good service history and 12 months MOT with no advisories and just serviced. Electric windows, electric door mirrors, alarm system. Excellent condition and drives extremely well. Great all round vehicle. Must be seen.

Vehicle registered: 01/12/2005
```

Looks very good condition and is a Ford Transit which @carolrmc is used to driving. 🚌 

![image](https://github.com/dwyl/phase-three/assets/194400/7efb9d03-5adf-4140-8bdd-1aaa603d88ac)

![image](https://github.com/dwyl/phase-three/assets/194400/ceb3adad-dba2-4e66-b328-15e793b77a3c)

![image](https://github.com/dwyl/phase-three/assets/194400/1f579bd3-0a7b-46d2-b674-1dd0f1c4c0b0)

![image](https://github.com/dwyl/phase-three/assets/194400/68aea1cd-4082-45ec-b44d-dc7f68a36e0e)

![image](https://github.com/dwyl/phase-three/assets/194400/8abf5bc4-062e-4d4d-8bf6-3d9b2923e58a)

![image](https://github.com/dwyl/phase-three/assets/194400/21140a9a-0a7a-406b-8860-74dcb3144724)

Appears to be left-hand-drive (so European): 
![image](https://github.com/dwyl/phase-three/assets/194400/04f2a9dc-67a6-4cdb-963c-1a72447bf447)

Interior plastics/cabin in good condition:
![image](https://github.com/dwyl/phase-three/assets/194400/ce3da56c-83a1-4765-94ae-d5c2364d5aa1)

For me the "con" of this van is that it only has one low-level bed and then the other will be above the cockpit.
Which is find _now_ but not great for access later in life. 💭

**Comment by nelsonic** [comment]
https://www.olx.pt/d/anuncio/autocaravana-mercedes-integral-IDIkrB2.html
<img width="1137" alt="image" src="https://github.com/dwyl/phase-three/assets/194400/2c6dda75-60c3-4117-8448-f0a4a09bd740">

**Comment by nelsonic** [comment]
Sadly, peak summer is no longer the time to be researching motorhomes 
as sellers know they can ask for more cash ... 💰 
Best time to start searching again will be October/November. 🔍 

Meanwhile we can finalise the _requirements_. 📝

**Comment by nelsonic** [comment]
As we enter October, we can begin our search again! 🔍 
e.g:  Hymer Camper:
[https://suchen.mobile.de/fahrzeuge/search.html?isSearchRequest=true&ms=%3B%3B%3BHymer&vc=Motorhome](https://suchen.mobile.de/fahrzeuge/search.html?isSearchRequest=true&ms=%3B%3B%3BHymer&p=10000%3A25000&ref=srp&refId=2ef2cbc3-4cba-90bb-58ca-2435b221b14e&s=Motorhome&sb=rel&vc=Motorhome)

[https://suchen.mobile.de/fahrzeuge/details.html?id=402670640](https://suchen.mobile.de/fahrzeuge/details.html?id=402670640&isSearchRequest=true&ms=%3B%3B%3BHymer&pageNumber=3&ref=srp&refId=949657c2-bf9c-4171-690f-0afc213073fc&s=Motorhome&sb=rel&searchId=949657c2-bf9c-4171-690f-0afc213073fc&vc=Motorhome)
<img width="1236" alt="image" src="https://github.com/user-attachments/assets/8b01a9db-fec2-4796-9cb3-6cf5af05e482">


In PT: 
https://www.standvirtual.com/autocaravanas/hymer
https://www.standvirtual.com/autocaravanas/anuncio/hymer-b-classic-ID8PJRLv.html
<img width="1224" alt="image" src="https://github.com/user-attachments/assets/c4a7d147-5b4a-4043-82ea-83a0934c727b">

https://www.standvirtual.com/autocaravanas?search%5Bfilter_float_price%3Afrom%5D=10000&search%5Bfilter_float_price%3Ato%5D=30000&search%5Border%5D=filter_float_price%3Aasc

https://www.olx.pt/d/anuncio/hymer-integral-b-574-IDIapCd.html
<img width="1224" alt="image" src="https://github.com/user-attachments/assets/e52a6e42-4360-42af-a401-d367eadd402a">

@carolrmc if you have time to do some research, please do. 🔍 🙏
