### ISSUE TITLE
London Cost of Living Survey

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phase-three#57]
In order to build our (biz) `case` for the `Braga House` we need `data`.
My _rough_ estimate is that _minimum_ monthly living costs in London are **£870**.
see: https://github.com/dwyl/phase-two/tree/1f423413127bf4d5afc9ea0bf69b1dc26843cc9e/braga#cost-of-living-in-london

But having some _real_ data from the members of the F&C/dwyl community would be _amazing_.

To that end I have drafted a Google Form questionnaire:
https://docs.google.com/a/dwyl.io/forms/d/1RSrXM-SxN4HHs0zISOiNlNNHKZK8HQvw2xGeeOkSqFE

@iteles I have made you the Owner. 
![image](https://cloud.githubusercontent.com/assets/194400/25575648/3068a61c-2e51-11e7-8ec3-5e90a8265f18.png)

# TODO:
+ [x] Add any questions you want collect data on.
+ [x] Get @sofer & @rebeccaradding's _feedback_ an add any question(s) they need data on for their Grant Applications. (_the data we are collecting is **very re-useable**!_)
+ [ ] sent out tomorrow on **_all_ communication channels** 
so we get as much data as possible.

Any questions, _please ask_! 
Thanks! ❤️  ✅  ☀️  🌱 🏡  🎉

**Comment by iteles** [comment]
I have added more context to the introductory sentence and would like to add a question on what people spend money on when given the chance to 'splurge' (i.e. what people find important as a 'lovely to have').

**Comment by iteles** [comment]
Have emailed the link to @sofer and @rebeccaradding with thoughts on specific usefulness to F&C. Ongoing 👍

**Comment by nelsonic** [comment]
@iteles did you get a _response_ on this? 🤔

**Comment by iteles** [comment]
I haven't forgotten this. I'm getting it sent out next week when the new cohort starts.
There have been a number of hold ups for various uninteresting reasons.

**Comment by nelsonic** [comment]
@iteles sweet! thanks for updating. ❤️

**Comment by iteles** [comment]
14 people answered the questionnaire.

Results are in:
<img width="408" alt="screen shot 2017-08-26 at 21 34 46" src="https://user-images.githubusercontent.com/4185328/29744916-7ae35168-8aa6-11e7-9dfe-814068f47d67.png">
<img width="323" alt="screen shot 2017-08-26 at 21 32 48" src="https://user-images.githubusercontent.com/4185328/29744917-7ae43c4a-8aa6-11e7-931e-513588e4ebd6.png">
<img width="352" alt="screen shot 2017-08-26 at 21 32 42" src="https://user-images.githubusercontent.com/4185328/29744918-7ae7f358-8aa6-11e7-9cd8-59da2ac74466.png">

<img width="511" alt="screen shot 2017-08-26 at 21 22 45" src="https://user-images.githubusercontent.com/4185328/29744921-80b4a704-8aa6-11e7-9c9a-f2b370d2751a.png">

+ Motivating factors for moving were two-fold: cheaper cost of living and access to tech jobs
+ Meals out and drinks were by far the most popular things that people spent money on as a luxury

**Comment by nelsonic** [comment]
@iteles thanks for updating. has the survey "_closed_"? 
could You/Dan encourage _more_ people to respond so that we have a more representative sample?

**Comment by iteles** [comment]
The survey hasn't closed, we'll look to encourage more responses when folks are back from reading week next week

**Comment by nelsonic** [comment]
@iteles would be _amaze_ to get a few more responses to this survey.
When would be the _best_ time to re-request that people answer it?
(_when are people back from holidays?_)

**Comment by nelsonic** [comment]
@iteles could you ask the _current_ cohort of F&C people to answer the questionnaire 
so that we _double_ our sample size?
